spring:
  application:
    name: client-service
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

# Configuración del API externo
external:
  api:
    connect-timeout: 10  # tiempo de conexión
    read-timeout: 30     # tiempo de lectura
    write-timeout: 30    # tiempo de escritura
    base-url: https://api.example.com
  # Configuración para el servicio de autenticación
  auth:
    url: /auth/token  # Endpoint para obtener tokens
    client-id: your-client-id
    client-secret: your-client-secret

# Configuración de logging
logging:
  level:
    root: INFO
    com.example.clientservice: DEBUG
    org.springframework.web: INFO
    retrofit2.http: DEBUG
  file:
    name: logs/client-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configuración de métricas y monitorización
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
  health:
    circuit-breakers:
      enabled: true